name: Build EDK2

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: System update
      run: sudo apt update 
    - name: Install build tools
      run: sudo apt install build-essential uuid-dev iasl git nasm python-is-python3 g++-aarch64-linux-gnu
    - name: Install mkbootimg
      run: git clone --depth 1 https://android.googlesource.com/platform/system/tools/mkbootimg /opt/mkbootimg-tools && echo '#!/bin/bash' | sudo tee /usr/local/bin/mkbootimg > /dev/null && echo 'python3 /opt/mkbootimg-tools/mkbootimg.py "$@"' | sudo tee -a /usr/local/bin/mkbootimg > /dev/null && sudo chmod +x /usr/local/bin/mkbootimg
      
    - name: Clone EDK2 repository
      run: git clone https://github.com/tianocore/edk2 --recursive -b edk2-stable202302

    - name: Clone EDK2 Platforms repository
      run: git clone https://github.com/tianocore/edk2-platforms.git
      
    - name: Run firstrun.sh
      run: |
        cp -r edk2* ../
        chmod +x ./firstrun.sh && ./firstrun.sh

    - name: Run build.sh
      run: chmod +x ./build.sh && ./build.sh
      
    - name: Upload boot-uefi.img artifact
      uses: actions/upload-artifact@v4
      with:
        name: boot-uefi-mt6765.img
        path: boot-uefi.img  # Adjust this path based on where the img file is generated
